# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: daa7265b0c20caf0b1eebd07fc33eab61a4ee6364e4fd51c4244d9b72be009f257a306bb9cd33c8208decd535fe67e90e3044fe215084091c4d05baddeadbf61

test:
  secret_key_base: 0310e5280ef0dda9ec18e4aff40243460fade90a5e0345f8048072602f24ded581400fb5b79fbb7d34011110de9af9a368103c417a871a692d25f5a14adbc262

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
